surf: Add `stats` property to each `DiffContent::Plain`
radicle-dev/radicle-git pull request #145
Opened 2023-09-29 11:54 UTC by sebastinez

This allows us to get the additions and deletions for each file in a diff.

2023-09-29 12:53 UTC, FintanH requested changes

2023-09-29 12:53 UTC, FintanH commented on radicle-surf/src/diff.rs
> +                eof,
```suggestion
                eof, ..
```
I'd say we just do this :)

2023-09-29 12:53 UTC, FintanH commented on radicle-surf/src/diff.rs
> +    pub fn stats(&self) -> FileStats {
```suggestion

    pub fn stats(&self) -> FileStats {
```
New line please :pray:

2023-09-29 12:53 UTC, FintanH commented on radicle-surf/src/diff.rs
> +        match &self {
Wait, why are we calculating the stats here if it's contained in `DiffContent::Plain`? :thinking: 

~I think we want to see if `git2` can provide the stats per file and get them from there when we create the `DiffContent` (in the `TryFrom` impls under `diff::git`).~

So we should just match and return:
```rust
DiffContent::Plain { stats, .. } => Some(stats),
DiffContent::Empty => None,
DiffContent::Binary => None,
```
I'd return an `Option` because stats don't make sense for the other two.

2023-09-29 12:53 UTC, FintanH commented on radicle-surf/src/diff/git.rs
> +                    git2::DiffLineType::Addition => {
Ah you are calculating them here. I checked `DiffFile` too and there were no individual stats.

2023-10-02 06:45 UTC, sebastinez commented on radicle-surf/src/diff.rs
> +        match &self {
Yeah that works, seems like it did the job twice 😁

2023-10-02 06:47 UTC, sebastinez commented on radicle-surf/src/diff/git.rs
> +                    git2::DiffLineType::Addition => {
I don't think we want the individual `stats` to show up in the `DiffFile` since we are interested in the changes introduced by a specific `diff` which is specified by `DiffContent`

2023-10-02 09:18 UTC, FintanH approved these changes
Just a little fix and then happy to merge :+1:

2023-10-02 09:18 UTC, FintanH commented on radicle-surf/t/src/diff.rs
> +                deletions:1
```suggestion
                additions: 2,
                deletions: 1
```

2023-10-02 09:29 UTC, sebastinez commented on radicle-surf/t/src/diff.rs
> +                deletions:1
Thanks for the catch, is resolved 👍

2023-10-02 09:39 UTC, merged