change last_commit() in Directory and File to be lazy
radicle-dev/radicle-git pull request #93
Opened 2023-01-05 22:13 UTC by keepsimple1

Also renamed "id" to "tree_id" in Directory and "blob_id" in File so that their meanings are clearer.

2023-01-05 22:22 UTC, keepsimple1 commented on radicle-surf/src/fs.rs
> +    snapshot_id: Oid,
I was debating if `parent_commit` is a better name, but eventually opted for `snapshot_id`. Let me know if any better names come up.

2023-01-05 22:36 UTC, keepsimple1 commented on radicle-surf/src/fs.rs
> +            .map_err(|_| error::File::InvalidPath(path.clone()))
We are losing / ignoring the `git::Error` from `Repository::last_commit` due to the challenge of chaining it into `error::File`. 

We could remove this method in this module so we won't call `repo.last_commit()`, but the underlying general error chaining issue still exists.

2023-01-09 19:01 UTC, keepsimple1 commented on radicle-surf/src/fs.rs
> -    pub fn last_commit(&self, repo: &Repository) -> Result<Commit, error::File> {
It is possible to remove this method, but we still need to have `snapshot_id` so that we can call `repo.last_commit` later.

2023-01-09 19:02 UTC, keepsimple1 commented on radicle-surf/t/src/file_system.rs
> +            .unwrap();
I think it's less ergonomic to call `repo.last_commit` compared with calling `dir.last_commit`.

2023-01-10 16:55 UTC, FintanH requested changes
I'm not convinced `File` and `Directory` need `snapshot_id` as part of their structs. They can both be associated with many `Oid`s and the need for which is the last one will depend on the context of what the user is browsing -- generally some branch name or a certain commit they are looking at.

2023-01-10 19:17 UTC, keepsimple1 commented
`snapshot_id` is a helper in the structs, in case the caller lost their context. Also, for a given `Directory`, calling `repo.last_commit()` with any context will return a fixed commit or None, because the underlying tree object is the same. 

That said, as we discussed, it is easier to add this `snapshot_id` or `last_commit()` method to `Directory` and `File` when they are needed. For now, we will not have them.

2023-01-11 10:44 UTC, FintanH approved these changes
I have some comments that I'm going to apply in the merge commit and push the changes :) Thanks for the work and conversation on these changes!

2023-01-11 10:44 UTC, FintanH commented on radicle-surf/src/fs.rs
> +        InvalidPath(PathBuf),
This isn't used :)

2023-01-11 10:44 UTC, FintanH commented on radicle-surf/src/fs.rs
> +    blob_id: Oid,
I'd rather we just stick with the `id` naming

2023-01-11 10:44 UTC, merged